services:
  - type: web
    name: tubeassist-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: VECTOR_STORE
        value: pinecone
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: tubeassist
      - key: PYTHON_VERSION
        value: 3.12.0