services:
  - type: web
    name: tubeassist-backend
    runtime: python
    rootDir: backend ## tell render to look inside backend folder 
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT ## $PORT=>  render will assign port dynamically 
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false ## render will prompt you to enter the env secret keys in Render Dashboard .
      - key: VECTOR_STORE
        value: pinecone
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: tubeassist
      - key: PYTHON_VERSION
        value: 3.11.0